### ISSUE TITLE
Som bruker av Altinn, ønsker jeg blir tryggere og inspirert til å løse oppgavene mine og bruke mulighetene i løsningen.

### ISSUE THREAD

**Issue by hansdragnes** [Altinn/dialogporten-frontend#1553]

**Comment by hansdragnes** [comment]
Dekkes av andre burkerhistorier

**Comment by LeifHelstad** [comment]
## Test

Dette er ikke mulig å måle. Setter TestStatus = NA

Ref:
_Som bruker av Altinn, ønsker jeg blir tryggere og inspirert til å løse oppgavene mine og bruke mulighetene i løsningen._

**Comment by knuthalvor** [comment]
Ikke noe arbeid som utføres her, endrer lukket tilstand og tar den også ut av epic.
